# Generated by Django 5.1.5 on 2025-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_account_post_like_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to="network.account"
            ),
        ),
    ]
