# Generated by Django 5.1.5 on 2025-04-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_account_following"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
